export const AGREGAR_TICKET = 'AGREGAR_TICKET';
export const AGREGAR_TICKET_EXITO = 'AGREGAR_TICKET_EXITO';
export const AGREGAR_TICKET_ERROR = 'AGREGAR_TICKET_ERROR';

export const COMENZAR_DESCARGA_TICKETES = 'COMENZAR_DESCARGA_TICKETES';
export const DESCARGAR_TICKETES_EXITO = 'DESCARGAR_TICKETES_EXITO';
export const DESCARGAR_TICKETES_ERROR = 'DESCARGAR_TICKETES_ERROR';

export const OBTENER_TICKET = 'OBTENER_TICKET';
export const TICKET_OBTENIDA_EXITO = 'TICKET_OBTENIDA_EXITO';
export const TICKET_OBTENIDA_ERROR = 'TICKET_OBTENIDA_ERROR';
